[tool.poetry]
name = "whuphf"
version = "0.1.0"
description = ""
authors = ["dhruv <dhruv.nigam93@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-fasthtml = "^0.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
